import { useGetBooksQuery } from '../../server/src/__generated__/types'

export default function Web() {
  // this hook is automatically generated by codegen
  const { loading, error, data } = useGetBooksQuery();

  if (loading) {
    return <p>Loading...</p>;
  }
  if (error) {
    return <p>Error :(</p>;
  }

  return (
    <div>
      <h1>Books</h1>
      {data.books.map(x => <div key={x.author + x.title}>{`${x.title} by: ${x.author}`}</div>)}
    </div>
  );
}
