import { useQuery } from '@apollo/client';
import { BooksUI } from '../ui-types';
import { GetBooksDocument } from '../../server/src/__generated__/queries';
// import { useGetBooksQuery } from '../../server/src/__generated__/queries'

export default function Web() {
  // hook automatically generated by codegen
  // const { loading, error, data } = useGetBooksQuery();
  const { loading, error, data } = useQuery<{ books: BooksUI }>(GetBooksDocument); // with customer type because of the transform
  console.log(data)

  if (loading) {
    return <p>Loading...</p>;
  }
  if (error) {
    return <p>Error :(</p>;
  }

  return (
    <div>
      <h1>Books</h1>
      {data.books.map(x => (
        <div key={x.id}>
          Title: {x.title} - Author: {x.author} - Score: {x.score}
        </div>
      ))}
    </div>
  );
}
